const mongoose = require('mongoose')

const SellerinformationSchema = new mongoose.Schema({
    firstName:{
        type:String,
        require:true,
        min:3,
        max:20,
        unique:true
    },
    lastName:{
        type:String,
        require:true,
        min:3,
        max:20,
        require:true
    },
    companyName:{
        type:String,
        unique:true
    },
    userID:{
        type:String,
        require:true,
        min:3,
        max:20,
        unique:true
    },
    password:{
        type:String,
        require:true,
        min:3,
        max:20
    },
    companyEmail:{
        type:String,
        require:true,
        min:3,
        max:50,
        unique:true
    },
    country:{
        type:String,
        require:true
    },
    description:{
        type:String,
        require:true,
        max:160
    },
    productsSold:{
        type:Array,
        default:[]
    },
    productsListed:{
        type:Array,
        default:[]
    },
    newOrders:{
        type:Array,
        default:[]
    },
    pendingOrders:{
        type:Array,
        default:[]
    },
    profileImage:{
        type:String,
        default:null
    }
},
{timestamps:true});

module.exports = mongoose.model("SellerInformation", SellerinformationSchema);